using System;
using System.Collections.Generic;
using System.Linq;

namespace PARAFactoNative.Services;

public static class UiTextTranslator
{
    private static readonly IReadOnlyDictionary<string, string> En = BuildEn();
    private static readonly IReadOnlyDictionary<string, string> Nl = BuildNl();
    private static readonly IReadOnlyList<KeyValuePair<string, string>> EnByLength = En.OrderByDescending(k => k.Key.Length).ToList();
    private static readonly IReadOnlyList<KeyValuePair<string, string>> NlByLength = Nl.OrderByDescending(k => k.Key.Length).ToList();
    private static readonly IReadOnlyDictionary<string, string> EnToFr = BuildReverse(En);
    private static readonly IReadOnlyDictionary<string, string> NlToFr = BuildReverse(Nl);
    private static readonly IReadOnlyList<KeyValuePair<string, string>> EnToFrByLength = EnToFr.OrderByDescending(k => k.Key.Length).ToList();
    private static readonly IReadOnlyList<KeyValuePair<string, string>> NlToFrByLength = NlToFr.OrderByDescending(k => k.Key.Length).ToList();

    public static string Translate(string? source)
    {
        var text = source ?? "";
        if (text.Length == 0) return text;
        var frenchBase = ToFrench(text);
        if (UiLanguageService.Current == UiLanguageService.Fr) return NormalizeFrenchDisplay(frenchBase);

        var dict = UiLanguageService.Current == UiLanguageService.Nl ? Nl : En;
        var repl = UiLanguageService.Current == UiLanguageService.Nl ? NlByLength : EnByLength;
        if (dict.TryGetValue(frenchBase, out var exact)) return exact;

        var output = frenchBase;
        foreach (var kv in repl)
        {
            if (output.Contains(kv.Key, StringComparison.Ordinal))
                output = output.Replace(kv.Key, kv.Value, StringComparison.Ordinal);
        }
        return output;
    }

    private static string NormalizeFrenchDisplay(string text)
        => text switch
        {
            "CREDIT_NOTE" => "NOTE DE CRÉDIT",
            _ => text
        };

    private static string ToFrench(string text)
    {
        if (EnToFr.TryGetValue(text, out var fromEnExact)) return fromEnExact;
        if (NlToFr.TryGetValue(text, out var fromNlExact)) return fromNlExact;

        var output = text;
        foreach (var kv in EnToFrByLength)
        {
            output = ReplaceTokenBounded(output, kv.Key, kv.Value);
        }
        foreach (var kv in NlToFrByLength)
        {
            output = ReplaceTokenBounded(output, kv.Key, kv.Value);
        }
        return output;
    }

    private static Dictionary<string, string> BuildReverse(IReadOnlyDictionary<string, string> src)
    {
        var reverse = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var kv in src)
        {
            if (!reverse.ContainsKey(kv.Value))
                reverse[kv.Value] = kv.Key;
        }
        return reverse;
    }

    private static string ReplaceTokenBounded(string input, string from, string to)
    {
        if (string.IsNullOrEmpty(input) || string.IsNullOrEmpty(from)) return input;

        var index = 0;
        var changed = false;
        var output = new System.Text.StringBuilder(input.Length + 16);
        while (true)
        {
            var hit = input.IndexOf(from, index, StringComparison.Ordinal);
            if (hit < 0) break;

            var before = hit == 0 ? '\0' : input[hit - 1];
            var afterIndex = hit + from.Length;
            var after = afterIndex >= input.Length ? '\0' : input[afterIndex];
            var leftOk = hit == 0 || !char.IsLetterOrDigit(before);
            var rightOk = afterIndex >= input.Length || !char.IsLetterOrDigit(after);

            if (leftOk && rightOk)
            {
                output.Append(input, index, hit - index);
                output.Append(to);
                index = afterIndex;
                changed = true;
            }
            else
            {
                output.Append(input, index, (hit - index) + from.Length);
                index = afterIndex;
            }
        }

        if (!changed) return input;
        output.Append(input, index, input.Length - index);
        return output.ToString();
    }

    private static Dictionary<string, string> BuildEn() => new(StringComparer.Ordinal)
    {
        ["Console"] = "Dashboard",
        ["Patients"] = "Patients",
        ["Tarifs"] = "Rates",
        ["Séances"] = "Sessions",
        ["Factures"] = "Invoices",
        ["Agenda RDV"] = "Appointments",
        ["Données techniques"] = "Technical Data",
        ["Aide"] = "Help",
        ["Patient"] = "Patient",
        ["Recherche:"] = "Search:",
        ["Code:"] = "Code:",
        ["Nom:"] = "Last name:",
        ["Prénom:"] = "First name:",
        ["Statut:"] = "Status:",
        ["Mutuelle:"] = "Health fund:",
        ["Mutuelle"] = "Health fund",
        ["Nouveau patient"] = "New patient",
        ["Modifier"] = "Edit",
        ["Rafraîchir"] = "Refresh",
        ["Nouveau"] = "New",
        ["Précédent"] = "Previous",
        ["Suivant"] = "Next",
        ["Encodage séance"] = "Session entry",
        ["Date:"] = "Date:",
        ["Date"] = "Date",
        ["Cash cabinet (acquittée)"] = "Cash in office (paid)",
        ["Tarif:"] = "Rate:",
        ["Tarif"] = "Rate",
        ["Tarif (BIM / NON BIM / PLEIN…)"] = "Rate (BIM / NON BIM / FULL...)",
        ["Part patient:"] = "Patient share:",
        ["Part mutuelle:"] = "Health fund share:",
        ["Part patient"] = "Patient share",
        ["Part mutuelle"] = "Health fund share",
        ["Lien agenda (RDV)"] = "Agenda link (appointment)",
        ["TOUTES"] = "ALL",
        ["PATIENT"] = "PATIENT",
        ["MUTUELLE"] = "HEALTH FUND",
        ["CREDIT_NOTE"] = "Credit note",
        ["Annuler perte"] = "Cancel loss",
        ["Modif mutuelle"] = "Health fund edit",
        ["Suppression du mois"] = "Month deletion",
        ["Supprimer toutes les factures du mois"] = "Delete all invoices for this month",
        ["Indexer destinataires (PDF)"] = "Index recipients (PDF)",
        ["Détails"] = "Details",
        ["Période"] = "Period",
        ["Période sélectionnée"] = "Selected period",
        ["TOTAL ENREGISTRÉ"] = "TOTAL RECORDED",
        ["Supprimer la ligne sélectionnée"] = "Delete selected row",
        ["Total patient:"] = "Patient total:",
        ["Total mutuelle:"] = "Health fund total:",
        ["Total général:"] = "Grand total:",
        ["Commentaire patient"] = "Patient comment",
        ["Fiche patient"] = "Patient file",
        ["Un clic sur une ligne charge directement la fiche. Le bouton Modifier enregistre les changements du patient sélectionné."] = "Click a row to load the file directly. The Edit button saves changes for the selected patient.",
        ["Rue:"] = "Street:",
        ["Numéro:"] = "Number:",
        ["Commentaire"] = "Comment",
        ["Actions séances"] = "Session actions",
        ["Ajouter séance"] = "Add session",
        ["Modifier la ligne"] = "Edit row",
        ["Effacer la ligne"] = "Delete row",
        ["ANNULATION"] = "UNDO",
        ["Actions journalier"] = "Daily actions",
        ["Générer PDF journalier"] = "Generate daily PDF",
        ["Ouvrir dossier Journaliers"] = "Open Daily folder",
        ["Actions factures"] = "Invoice actions",
        ["Générer factures patients"] = "Generate patient invoices",
        ["Générer factures mutuelles"] = "Generate health fund invoices",
        ["Ouvrir dossier factures patients du mois"] = "Open monthly patient invoices folder",
        ["Ouvrir dossier factures mutuelle du mois"] = "Open monthly health fund invoices folder",
        ["Séances du jour"] = "Today sessions",
        ["IMPORTER AGENDA"] = "IMPORT APPOINTMENTS",
        ["Rendez-vous"] = "Appointment",
        ["Rendez-vous concerné :"] = "Concerned appointment:",
        ["Début de journée (premier RDV possible)"] = "Day start (first possible appointment)",
        ["Fin de journée (dernière fin de séance autorisée)"] = "Day end (latest allowed session end)",
        ["Arrêt lunch ?"] = "Lunch break enabled?",
        ["Retour au lunch récurrent"] = "Back to recurring lunch",
        ["Heure de début"] = "Start time",
        ["Durée de la séance"] = "Session duration",
        ["30 minutes"] = "30 minutes",
        ["1 heure"] = "1 hour",
        ["Autre (heures et minutes…)"] = "Other (hours and minutes...)",
        ["minutes"] = "minutes",
        ["Encodage récurrent"] = "Recurring entry",
        ["Copier journée jusqu'à date"] = "Copy day until date",
        ["Supprimer journée"] = "Delete day",
        ["Le tarif est prérempli selon le statut du patient (fiche). Vous pouvez le changer."] = "Rate is prefilled according to patient status (file). You can change it.",
        ["Vue :"] = "View:",
        ["Aujourd'hui"] = "Today",
        ["Indisponibilité"] = "Unavailability",
        ["lun."] = "Mon.",
        ["mar."] = "Tue.",
        ["mer."] = "Wed.",
        ["jeu."] = "Thu.",
        ["ven."] = "Fri.",
        ["sam."] = "Sat.",
        ["dim."] = "Sun.",
        ["Créneau disponible"] = "Available slot",
        ["Indisponible"] = "Unavailable",
        ["Code"] = "Code",
        ["Nom"] = "Last name",
        ["Prénom"] = "First name",
        ["Téléphone"] = "Phone",
        ["Référent"] = "Referrer",
        ["Référend"] = "Referrer",
        ["Date presc"] = "Prescription date",
        ["Date accord"] = "Approval date",
        ["Période accord"] = "Approval period",
        ["Nomenclature"] = "Prescription code",
        ["Médecin"] = "Doctor",
        ["médecin"] = "doctor",
        ["Infos médicales"] = "Medical information",
        ["infos médicales"] = "medical information",
        ["Nom médecin"] = "Doctor last name",
        ["Nom médecin:"] = "Doctor last name:",
        ["Nom médecin :"] = "Doctor last name:",
        ["Nomenclature:"] = "Prescription code:",
        ["Prénom médecin :"] = "Doctor first name:",
        ["Code médecin :"] = "Doctor code:",
        ["Médecin et prescriptions"] = "Doctor and prescriptions",
        ["Nouveau patient - erreur"] = "New patient - error",
        ["Modifier patient - erreur"] = "Edit patient - error",
        ["Lister séances - erreur"] = "List sessions - error",
        ["Éditer journalier - erreur"] = "Edit daily report - error",
        ["Ouvrir dossier journaliers - erreur"] = "Open daily folder - error",
        ["Ouvrir dossier factures du mois - erreur"] = "Open monthly invoices folder - error",
        ["Ouvrir dossier factures mutuelles du mois - erreur"] = "Open monthly health fund invoices folder - error",
        ["Générer factures patients - erreur"] = "Generate patient invoices - error",
        ["Générer factures mutuelles - erreur"] = "Generate health fund invoices - error",
        ["PARAFacto - Email"] = "PARAFacto - Email",
        ["PARAFacto - Sauvegarde DB"] = "PARAFacto - DB backup",
        ["Les PDFs ont été générés, mais l'envoi e-mail a échoué."] = "PDFs were generated, but email sending failed.",
        ["Envoi DB (sauvegarde) impossible."] = "DB backup email sending failed.",
        ["Impossible d'ouvrir le portail clients :"] = "Unable to open customer portal:",
        ["PARAFacto — Conformité"] = "PARAFacto — Compliance",
        ["Votre acceptation a été enregistrée. Une preuve locale (horodatage, versions des documents et empreintes des textes) a été ajoutée au fichier d'audit."] = "Your acceptance has been recorded. Local proof (timestamp, document versions and text hashes) has been added to the audit file.",
        ["L’heure de début de journée doit être au moins 15 minutes avant la fin de journée."] = "Day start must be at least 15 minutes before day end.",
        ["L’heure de fin de journée doit être au moins 15 minutes après le début de journée."] = "Day end must be at least 15 minutes after day start.",
        ["Les jours passés ne peuvent pas être modifiés (indisponibilités)."] = "Past days cannot be modified (unavailability).",
        ["Plage de lunch invalide."] = "Invalid lunch period.",
        ["Heure invalide (utilisez le format HH:mm)."] = "Invalid time (use HH:mm format).",
        ["Impossible d’utiliser ce créneau comme premier rendez-vous : vous êtes indisponible."] = "This slot cannot be used as first appointment: you are unavailable.",
        ["Ce créneau chevauche un autre rendez-vous. Corrigez l’heure ou le jour avant un encodage récurrent."] = "This slot overlaps another appointment. Adjust time or day before recurring entry.",
        ["Aucune date ne correspond aux critères choisis."] = "No date matches the selected criteria.",
        ["Agenda — récurrence"] = "Schedule — recurrence",
        ["Agenda — récurrence (chevauchements)"] = "Schedule — recurrence (overlaps)",
        ["Agenda — copie journée"] = "Schedule — day copy",
        ["Agenda — suppression journée"] = "Schedule — day deletion",
        ["Agenda — déplacement"] = "Schedule — move",
        ["Agenda — chargement"] = "Schedule — loading",
        ["Agenda — enregistrement"] = "Schedule — save",
        ["Agenda — lunch"] = "Schedule — lunch",
        ["Aucun rendez-vous à copier pour cette journée."] = "No appointment to copy for this day.",
        ["La date de fin doit être postérieure à la journée source."] = "End date must be after source day.",
        ["Suppression effectuée."] = "Deletion completed.",
        ["Impossible de réserver ce créneau, vous êtes indisponible"] = "Cannot book this slot, you are unavailable",
        ["Ce créneau chevauche un autre rendez-vous : même heure de début ou plages horaires qui se recouvrent."] = "This slot overlaps another appointment: same start time or overlapping periods.",
        ["Impossible de scinder : un conflit est détecté sur au moins un des deux créneaux de 30 minutes."] = "Cannot split: conflict detected on at least one of the two 30-minute slots.",
        ["Impossible de scinder : au moins un des deux créneaux de 30 minutes chevauche la pause lunch."] = "Cannot split: at least one of the two 30-minute slots overlaps lunch break.",
        ["Choisissez la nouvelle heure de début et la durée de la pause. La plage s’affichera en jaune dans l’agenda pour cette date seulement."] = "Choose the new start time and break duration. The period will appear in yellow in the schedule for this date only.",
        ["Reporter le lunch (ce jour uniquement)"] = "Reschedule lunch (this day only)",
        ["Horaires de travail (ce jour)"] = "Working hours (this day)",
        ["Définissez l’heure de début et de fin de journée pour cette date uniquement. Les créneaux de rendez-vous et l’affichage du calendrier s’adaptent. Les horaires habituels (panneau de gauche) ne sont pas modifiés."] = "Set start and end working hours for this date only. Appointment slots and calendar display will adapt. Regular hours (left panel) are unchanged.",
        ["Horaires du jour"] = "Day schedule",
        ["Politique de confidentialité et conditions d'utilisation"] = "Privacy policy and terms of use",
        ["Politique de confidentialité (RGPD, mineurs, données de santé)"] = "Privacy policy (GDPR, minors, health data)",
        ["Conditions générales d'utilisation du service"] = "General terms of service",
        ["J'ai lu la politique de confidentialité et je l'accepte pour la version affichée ci-dessus."] = "I have read and accept the privacy policy for the version displayed above.",
        ["J'ai lu les conditions d'utilisation du service et je les accepte pour la version affichée ci-dessus."] = "I have read and accept the terms of service for the version displayed above.",
        ["Enregistrer mon acceptation (preuve locale)"] = "Save my acceptance (local proof)",
        ["Abonnement PARAFacto"] = "PARAFacto subscription",
        ["Portail clients Stripe"] = "Stripe customer portal",
        ["Permet aux abonnés de gérer leur carte bancaire, leurs factures et leur abonnement (selon les options activées dans Stripe)."] = "Allows subscribers to manage payment card, invoices and subscription (depending on options enabled in Stripe).",
        ["Email d'envoi de sauvegarde des fichiers journaliers et factures"] = "Backup destination email for daily files and invoices",
        ["Utiliser SMTP (Gmail/Autre) si Outlook absent"] = "Use SMTP (Gmail/Other) if Outlook is unavailable",
        ["Port :"] = "Port:",
        ["From (optionnel) :"] = "From (optional):",
        ["Mot de passe app :"] = "App password:",
        ["Workspace introuvable.\nChoisis d'abord le workspace."] = "Workspace not found.\nSelect the workspace first.",
        ["Accès portail clients"] = "Customer portal access",
        ["Email :"] = "Email:",
        ["Utilisateur :"] = "Username:",
        ["Fermer"] = "Close",
        ["Annuler"] = "Cancel",
        ["Enregistrer"] = "Save",
        ["Supprimer"] = "Delete",
        ["Actif"] = "Active",
        ["Confirmer"] = "Confirm",
        ["Retour"] = "Back",
        ["Oui"] = "Yes",
        ["Non"] = "No",
        ["Erreur"] = "Error",
        ["Avertissement"] = "Warning",
        ["Information"] = "Information",
        ["Agenda"] = "Schedule",
        ["Lunch"] = "Lunch",
        ["Heure de fin"] = "End time",
        ["Durée (minutes)"] = "Duration (minutes)",
        ["Début de journée"] = "Day start",
        ["Fin de journée"] = "Day end",
        ["Choisissez une date."] = "Please choose a date.",
        ["Choisissez l’heure de début et de fin."] = "Please choose start and end times.",
        ["Heures invalides."] = "Invalid times.",
        ["L’heure de fin doit être après l’heure de début."] = "End time must be after start time.",
        ["Sélectionnez une ligne à supprimer."] = "Select a row to delete.",
        ["Workspace introuvable."] = "Workspace not found.",
        ["PARAFacto — Erreur"] = "PARAFacto — Error",
        ["Impossible d'ouvrir"] = "Unable to open",
        ["Ouvrir la page"] = "Open page",
        ["Ouvrir le dossier"] = "Open folder",
        ["Ouvrir l'onglet Données techniques"] = "Open Technical Data tab",
        ["Une nouvelle version de la politique de confidentialité et/ou des conditions d'utilisation est fournie avec cette mise à jour. Ouvrez l'onglet « Données techniques » (bouton ci-dessous), lisez les textes et acceptez-les — vous ne pourrez pas utiliser les autres onglets tant que ce n'est pas fait. Merci aussi d'ajouter une adresse e-mail d'envoi des copies de vos documents PDF si vous le désirez (section courriel du même onglet)."] =
            "A new version of the privacy policy and/or terms of use is included with this update. Open the Technical Data tab (button below), read the texts and accept them — you cannot use the other tabs until this is done. Please also add an email address for sending copies of your PDF documents if you wish (email section of the same tab).",
        ["Ouvrez l'onglet « Données techniques » (bouton ci-dessous), lisez et acceptez la politique de confidentialité ainsi que les conditions d'utilisation. Merci aussi d'ajouter une adresse e-mail d'envoi des copies de vos documents PDF si vous le désirez (section courriel du même onglet)."] =
            "Open the Technical Data tab (button below), read and accept the privacy policy and terms of use. Please also add an email address for sending copies of your PDF documents if you wish (email section of the same tab).",
        ["Les textes de la politique de confidentialité et/ou des conditions d'utilisation sont introuvables ou vides (installation incomplète ou version ancienne). Vous pouvez utiliser la console : suivez la bannière « nouvelle version » ou téléchargez la dernière version du site, puis réinstallez. Ensuite, revenez ici pour lire et accepter les documents."] =
            "The privacy policy and/or terms of use texts are missing or empty (incomplete installation or old version). You can use the dashboard: follow the \"new version\" banner or download the latest version from the website, then reinstall. Then return here to read and accept the documents.",
        ["Les documents juridiques ont été mis à jour (nouvelle version publiée avec l'application). Lisez les textes ci-dessous, cochez les deux cases puis enregistrez votre acceptation — les autres onglets restent masqués par le message tant que ce n'est pas fait."] =
            "The legal documents have been updated (new version shipped with the application). Read the texts below, check both boxes then save your acceptance — the other tabs stay hidden by this message until this is done.",
        ["Veuillez lire les documents ci-dessous, cocher les deux cases puis enregistrer votre acceptation."] =
            "Please read the documents below, check both boxes then save your acceptance.",
        ["Fichiers juridiques introuvables dans le dossier d'installation (sous-dossier Legal). Réinstallez l'application ou contactez le support."] =
            "Legal files were not found in the installation folder (Legal subfolder). Reinstall the application or contact support.",
        ["Impossible de charger les documents : "] =
            "Unable to load documents: ",
        ["Cash patient :"] = "Patient cash:",
        ["Facturé patient :"] = "Billed to patient:",
        ["Total tiers payant :"] = "Third-party payer total:",
        ["Facturé mutuelle :"] = "Billed to health fund:",
        ["Montant total du jour :"] = "Total amount of the day:",
        ["Jour"] = "Day",
        ["Mois"] = "Month",
        ["Année"] = "Year",
        ["Semaine"] = "Week",
        ["TOUTES"] = "ALL",
        ["IMPAYEE"] = "UNPAID",
        ["PARTIELLE"] = "PARTIAL",
        ["PAYEE"] = "PAID",
        ["ACQUITTEE"] = "SETTLED",
        ["PERTE"] = "LOSS",
        ["MODIFIEE"] = "MODIFIED",
        ["PATIENT"] = "PATIENT",
        ["MUTUELLE"] = "HEALTH FUND",
        ["CREDIT_NOTE"] = "CREDIT NOTE",
        ["Libellé"] = "Label",
        ["Statut"] = "Status",
        ["Adresse"] = "Address",
        ["Ville"] = "City",
        ["Pays"] = "Country",
        ["Le mois "] = "Month ",
        [" est modifiable."] = " is editable.",
        [" est verrouillé car des factures existent déjà."] = " is locked because invoices already exist.",
        ["Définissez une plage horaire pendant laquelle vous ne pouvez pas recevoir de rendez-vous. Elle apparaît en rouge dans le calendrier."] = "Set a time period during which you cannot receive appointments. It appears in red in the calendar.",
        ["Prénom médecin"] = "Doctor first name",
        ["Code médecin"] = "Doctor code",
        ["Prénom médecin:"] = "Doctor first name:",
        ["Code médecin:"] = "Doctor code:",
        ["Date paiement"] = "Payment date",
        ["Facturé à"] = "Billed to",
        ["TOTAL ENREGISTRÉ"] = "TOTAL RECORDED",
        ["PAYE"] = "PAID",
        ["PAYE : "] = "PAID: ",
        ["Toutes les périodes"] = "All periods",
        ["De 'date' à 'date'"] = "From 'date' to 'date'",
        ["Année / Semaine"] = "Year / Week",
        ["Année / Mois"] = "Year / Month",
        ["Année / Trimestre"] = "Year / Quarter",
        ["Dernière année complète"] = "Last full year",
        ["Année courante"] = "Current year",
        ["Trimestre courant"] = "Current quarter",
        ["Période sélectionnée"] = "Selected period",
        ["Perte"] = "Loss",
        ["Solde"] = "Balance",
        ["Jour férié :"] = "Public holiday:",
        ["Ces horaires sont mémorisés au lancement suivant. La liste « Heure de début » s’y adapte. Les RDV déjà enregistrés hors plage restent inchangés jusqu’à modification manuelle."] = "These hours are remembered at next startup. The \"Start time\" list adapts to them. Existing appointments outside this range remain unchanged until manually edited.",
        ["Tarif RDV:"] = "Appointment rate:",
        ["Données professionnelles"] = "Practice details",
        ["Ces informations apparaissent sur les factures patients, notes de crédit, factures acquittées et états récapitulatifs mutuelles. Le logo et le titre sont aussi affichés dans la console."] = "These details appear on patient invoices, credit notes, settled invoices, and mutual insurance summary statements. The logo and title are also shown on the dashboard.",
        ["Recharger depuis le disque"] = "Reload from disk",
        ["Logo (aperçu)"] = "Logo (preview)",
        ["Choisir une image…"] = "Choose image…",
        ["Retirer le logo"] = "Remove logo",
        ["Console — titre à côté du logo"] = "Dashboard — title next to the logo",
        ["Factures / NC — nom ou titre du praticien (ligne principale)"] = "Invoices / credit notes — practitioner name or title (main line)",
        ["Rappels factures (signature WhatsApp / mail)"] = "Invoice reminders (WhatsApp / email signature)",
        ["Adresse et coordonnées (bloc facture patient)"] = "Address and contact (patient invoice block)",
        ["Adresse ligne 1"] = "Address line 1",
        ["Adresse ligne 2 (ex. CP Ville)"] = "Address line 2 (e.g. postcode, city)",
        ["N° INAMI"] = "INAMI number",
        ["N° TVA"] = "VAT number",
        ["E-mail"] = "Email",
        ["Paiements (IBAN / BIC)"] = "Payments (IBAN / BIC)",
        ["IBAN (factures patients / NC)"] = "IBAN (patient invoices / credit notes)",
        ["IBAN (état mutuelle)"] = "IBAN (mutual insurance statement)",
        ["IBAN (notes de crédit — optionnel)"] = "IBAN (credit notes — optional)",
        ["État récapitulatif mutuelle"] = "Mutual insurance summary statement",
        ["Ligne « Nom et prénom du prestataire » et adresse complète sur une seule ligne. Si l\u2019adresse dédiée est vide, les lignes 1 et 2 ci-dessus sont combinées."] = "\u201cCare provider name\u201d line and full address on a single line. If the dedicated address is empty, lines 1 and 2 above are combined.",
        ["Nom et prénom (ex. DUPONT Jean)"] = "Name (e.g. DOE Jane)",
        ["Adresse (une ligne, optionnel)"] = "Address (one line, optional)",
    };

    private static Dictionary<string, string> BuildNl() => new(StringComparer.Ordinal)
    {
        ["Console"] = "Console",
        ["Patients"] = "Patiënten",
        ["Tarifs"] = "Tarieven",
        ["Séances"] = "Sessies",
        ["Factures"] = "Facturen",
        ["Agenda RDV"] = "Afspraken",
        ["Données techniques"] = "Technische Gegevens",
        ["Aide"] = "Hulp",
        ["Patient"] = "Patiënt",
        ["Recherche:"] = "Zoeken:",
        ["Code:"] = "Code:",
        ["Nom:"] = "Naam:",
        ["Prénom:"] = "Voornaam:",
        ["Statut:"] = "Status:",
        ["Mutuelle:"] = "Mutualiteit:",
        ["Mutuelle"] = "Mutualiteit",
        ["Nouveau patient"] = "Nieuwe patiënt",
        ["Modifier"] = "Bewerken",
        ["Rafraîchir"] = "Vernieuwen",
        ["Nouveau"] = "Nieuw",
        ["Date"] = "Datum",
        ["Encodage séance"] = "Sessie-invoer",
        ["Date:"] = "Datum:",
        ["Cash cabinet (acquittée)"] = "Cash in kabinet (betaald)",
        ["Tarif:"] = "Tarief:",
        ["Part patient:"] = "Deel patiënt:",
        ["Part mutuelle:"] = "Deel mutualiteit:",
        ["Part patient"] = "Deel patiënt",
        ["Part mutuelle"] = "Deel mutualiteit",
        ["Lien agenda (RDV)"] = "Agenda-link (afspraak)",
        ["TOUTES"] = "ALLE",
        ["PATIENT"] = "PATIËNT",
        ["MUTUELLE"] = "MUTUALITEIT",
        ["CREDIT_NOTE"] = "Creditnota",
        ["Annuler perte"] = "Verlies annuleren",
        ["Modif mutuelle"] = "Mutualiteit wijzigen",
        ["Suppression du mois"] = "Verwijderen van de maand",
        ["Supprimer toutes les factures du mois"] = "Alle facturen van deze maand verwijderen",
        ["Indexer destinataires (PDF)"] = "Ontvangers indexeren (PDF)",
        ["Détails"] = "Details",
        ["Période"] = "Periode",
        ["Période sélectionnée"] = "Geselecteerde periode",
        ["TOTAL ENREGISTRÉ"] = "TOTAAL GEREGISTREERD",
        ["Supprimer la ligne sélectionnée"] = "Geselecteerde rij verwijderen",
        ["Total patient:"] = "Totaal patiënt:",
        ["Total mutuelle:"] = "Totaal mutualiteit:",
        ["Total général:"] = "Algemeen totaal:",
        ["Commentaire"] = "Opmerking",
        ["Fiche patient"] = "Patiëntfiche",
        ["Un clic sur une ligne charge directement la fiche. Le bouton Modifier enregistre les changements du patient sélectionné."] = "Klik op een rij om de fiche direct te laden. De knop Bewerken slaat de wijzigingen van de geselecteerde patiënt op.",
        ["Rue:"] = "Straat:",
        ["Numéro:"] = "Nummer:",
        ["Actions séances"] = "Sessieacties",
        ["Ajouter séance"] = "Sessie toevoegen",
        ["Modifier la ligne"] = "Rij bewerken",
        ["Effacer la ligne"] = "Rij verwijderen",
        ["ANNULATION"] = "ONGEDAAN",
        ["Actions journalier"] = "Dagelijkse acties",
        ["Générer PDF journalier"] = "Dagelijkse PDF maken",
        ["Ouvrir dossier Journaliers"] = "Map Dagelijks openen",
        ["Actions factures"] = "Factuuracties",
        ["Générer factures patients"] = "Patiëntfacturen maken",
        ["Générer factures mutuelles"] = "Mutualiteitsfacturen maken",
        ["Ouvrir dossier factures patients du mois"] = "Map maandelijkse patiëntfacturen openen",
        ["Ouvrir dossier factures mutuelle du mois"] = "Map maandelijkse mutualiteitsfacturen openen",
        ["Séances du jour"] = "Sessies van vandaag",
        ["IMPORTER AGENDA"] = "AGENDA IMPORTEREN",
        ["Rendez-vous"] = "Afspraak",
        ["Début de journée (premier RDV possible)"] = "Begin van de dag (eerste mogelijke afspraak)",
        ["Fin de journée (dernière fin de séance autorisée)"] = "Einde van de dag (laatste toegelaten sessie-einde)",
        ["Arrêt lunch ?"] = "Lunchpauze actief?",
        ["Retour au lunch récurrent"] = "Terug naar terugkerende lunch",
        ["Heure de début"] = "Startuur",
        ["Durée de la séance"] = "Sessieduur",
        ["30 minutes"] = "30 minuten",
        ["1 heure"] = "1 uur",
        ["Autre (heures et minutes…)"] = "Andere (uren en minuten...)",
        ["minutes"] = "minuten",
        ["Encodage récurrent"] = "Terugkerende invoer",
        ["Copier journée jusqu'à date"] = "Dag kopiëren tot datum",
        ["Supprimer journée"] = "Dag verwijderen",
        ["Vue :"] = "Weergave:",
        ["Aujourd'hui"] = "Vandaag",
        ["lun."] = "ma.",
        ["mar."] = "di.",
        ["mer."] = "wo.",
        ["jeu."] = "do.",
        ["ven."] = "vr.",
        ["sam."] = "za.",
        ["dim."] = "zo.",
        ["Créneau disponible"] = "Beschikbaar tijdslot",
        ["Indisponible"] = "Onbeschikbaar",
        ["Rendez-vous concerné :"] = "Betrokken afspraak:",
        ["Code"] = "Code",
        ["Nom"] = "Naam",
        ["Prénom"] = "Voornaam",
        ["Téléphone"] = "Telefoon",
        ["Référent"] = "Verwijzer",
        ["Référend"] = "Verwijzer",
        ["Date presc"] = "Voorschriftdatum",
        ["Date accord"] = "Goedkeuringsdatum",
        ["Période accord"] = "Goedkeuringsperiode",
        ["Nomenclature"] = "Voorschriftcode",
        ["Médecin"] = "Arts",
        ["médecin"] = "arts",
        ["Infos médicales"] = "Medische info",
        ["infos médicales"] = "medische info",
        ["Nom médecin"] = "Naam arts",
        ["Nom médecin:"] = "Naam arts:",
        ["Nom médecin :"] = "Naam arts:",
        ["Nomenclature:"] = "Voorschriftcode:",
        ["Prénom médecin :"] = "Voornaam arts:",
        ["Code médecin :"] = "Code arts:",
        ["Médecin et prescriptions"] = "Arts en voorschriften",
        ["Nouveau patient - erreur"] = "Nieuwe patiënt - fout",
        ["Modifier patient - erreur"] = "Patiënt bewerken - fout",
        ["Lister séances - erreur"] = "Sessies weergeven - fout",
        ["Éditer journalier - erreur"] = "Dagrapport bewerken - fout",
        ["Ouvrir dossier journaliers - erreur"] = "Map dagrapporten openen - fout",
        ["Ouvrir dossier factures du mois - erreur"] = "Map maandfacturen openen - fout",
        ["Ouvrir dossier factures mutuelles du mois - erreur"] = "Map maandelijkse mutualiteitsfacturen openen - fout",
        ["Générer factures patients - erreur"] = "Patiëntfacturen maken - fout",
        ["Générer factures mutuelles - erreur"] = "Mutualiteitsfacturen maken - fout",
        ["PARAFacto - Sauvegarde DB"] = "PARAFacto - DB-back-up",
        ["Les PDFs ont été générés, mais l'envoi e-mail a échoué."] = "PDF's zijn aangemaakt, maar e-mail verzenden is mislukt.",
        ["Envoi DB (sauvegarde) impossible."] = "DB-back-up e-mail verzenden mislukt.",
        ["Impossible d'ouvrir le portail clients :"] = "Kan klantenportaal niet openen:",
        ["PARAFacto — Conformité"] = "PARAFacto — Naleving",
        ["Votre acceptation a été enregistrée. Une preuve locale (horodatage, versions des documents et empreintes des textes) a été ajoutée au fichier d'audit."] = "Uw akkoord is geregistreerd. Lokaal bewijs (tijdstempel, documentversies en tekst-hashes) werd toegevoegd aan het auditbestand.",
        ["Abonnement PARAFacto"] = "PARAFacto-abonnement",
        ["Portail clients Stripe"] = "Stripe-klantenportaal",
        ["Accès portail clients"] = "Toegang klantenportaal",
        ["L’heure de début de journée doit être au moins 15 minutes avant la fin de journée."] = "Beginuur van de dag moet minstens 15 minuten voor het einduur liggen.",
        ["L’heure de fin de journée doit être au moins 15 minutes après le début de journée."] = "Einduur van de dag moet minstens 15 minuten na het beginuur liggen.",
        ["Les jours passés ne peuvent pas être modifiés (indisponibilités)."] = "Voorbije dagen kunnen niet worden gewijzigd (onbeschikbaarheid).",
        ["Plage de lunch invalide."] = "Ongeldige lunchperiode.",
        ["Heure invalide (utilisez le format HH:mm)."] = "Ongeldig uur (gebruik formaat HH:mm).",
        ["Impossible d’utiliser ce créneau comme premier rendez-vous : vous êtes indisponible."] = "Dit tijdslot kan niet als eerste afspraak worden gebruikt: u bent onbeschikbaar.",
        ["Ce créneau chevauche un autre rendez-vous. Corrigez l’heure ou le jour avant un encodage récurrent."] = "Dit tijdslot overlapt een andere afspraak. Pas uur of dag aan vóór terugkerende invoer.",
        ["Aucune date ne correspond aux critères choisis."] = "Geen datum komt overeen met de gekozen criteria.",
        ["Agenda — récurrence"] = "Agenda — herhaling",
        ["Agenda — récurrence (chevauchements)"] = "Agenda — herhaling (overlappingen)",
        ["Agenda — copie journée"] = "Agenda — dag kopiëren",
        ["Agenda — suppression journée"] = "Agenda — dag verwijderen",
        ["Agenda — déplacement"] = "Agenda — verplaatsen",
        ["Agenda — chargement"] = "Agenda — laden",
        ["Agenda — enregistrement"] = "Agenda — opslaan",
        ["Agenda — lunch"] = "Agenda — lunch",
        ["Aucun rendez-vous à copier pour cette journée."] = "Geen afspraken om te kopiëren voor deze dag.",
        ["La date de fin doit être postérieure à la journée source."] = "Einddatum moet na de brondag liggen.",
        ["Suppression effectuée."] = "Verwijderen uitgevoerd.",
        ["Impossible de réserver ce créneau, vous êtes indisponible"] = "Kan dit tijdslot niet boeken, u bent onbeschikbaar",
        ["Ce créneau chevauche un autre rendez-vous : même heure de début ou plages horaires qui se recouvrent."] = "Dit tijdslot overlapt een andere afspraak: hetzelfde beginuur of overlappende periodes.",
        ["Impossible de scinder : un conflit est détecté sur au moins un des deux créneaux de 30 minutes."] = "Splitsen niet mogelijk: conflict gedetecteerd op minstens één van de twee tijdslots van 30 minuten.",
        ["Impossible de scinder : au moins un des deux créneaux de 30 minutes chevauche la pause lunch."] = "Splitsen niet mogelijk: minstens één van de twee tijdslots van 30 minuten overlapt de lunchpauze.",
        ["Choisissez la nouvelle heure de début et la durée de la pause. La plage s’affichera en jaune dans l’agenda pour cette date seulement."] = "Kies het nieuwe beginuur en de duur van de pauze. De periode verschijnt in geel in de agenda voor alleen deze datum.",
        ["Reporter le lunch (ce jour uniquement)"] = "Lunch verplaatsen (alleen deze dag)",
        ["Horaires de travail (ce jour)"] = "Werkuren (deze dag)",
        ["Définissez l’heure de début et de fin de journée pour cette date uniquement. Les créneaux de rendez-vous et l’affichage du calendrier s’adaptent. Les horaires habituels (panneau de gauche) ne sont pas modifiés."] = "Stel begin- en einduur van de dag in voor alleen deze datum. Afspraaktijden en kalenderweergave worden aangepast. Gewone uren (linkerpaneel) blijven ongewijzigd.",
        ["Horaires du jour"] = "Daguren",
        ["Politique de confidentialité et conditions d'utilisation"] = "Privacybeleid en gebruiksvoorwaarden",
        ["Politique de confidentialité (RGPD, mineurs, données de santé)"] = "Privacybeleid (AVG, minderjarigen, gezondheidsgegevens)",
        ["Conditions générales d'utilisation du service"] = "Algemene gebruiksvoorwaarden van de dienst",
        ["J'ai lu la politique de confidentialité et je l'accepte pour la version affichée ci-dessus."] = "Ik heb het privacybeleid gelezen en aanvaard het voor de hierboven weergegeven versie.",
        ["J'ai lu les conditions d'utilisation du service et je les accepte pour la version affichée ci-dessus."] = "Ik heb de gebruiksvoorwaarden gelezen en aanvaard ze voor de hierboven weergegeven versie.",
        ["Enregistrer mon acceptation (preuve locale)"] = "Mijn aanvaarding opslaan (lokaal bewijs)",
        ["Permet aux abonnés de gérer leur carte bancaire, leurs factures et leur abonnement (selon les options activées dans Stripe)."] = "Laat abonnees hun bankkaart, facturen en abonnement beheren (afhankelijk van ingeschakelde opties in Stripe).",
        ["Email d'envoi de sauvegarde des fichiers journaliers et factures"] = "Back-up e-mailadres voor dagbestanden en facturen",
        ["Utiliser SMTP (Gmail/Autre) si Outlook absent"] = "SMTP gebruiken (Gmail/Anders) als Outlook ontbreekt",
        ["Port :"] = "Poort:",
        ["From (optionnel) :"] = "Van (optioneel):",
        ["Mot de passe app :"] = "App-wachtwoord:",
        ["Workspace introuvable.\nChoisis d'abord le workspace."] = "Workspace niet gevonden.\nKies eerst de workspace.",
        ["Annuler"] = "Annuleren",
        ["Enregistrer"] = "Opslaan",
        ["Supprimer"] = "Verwijderen",
        ["Actif"] = "Actief",
        ["Confirmer"] = "Bevestigen",
        ["Oui"] = "Ja",
        ["Non"] = "Nee",
        ["Erreur"] = "Fout",
        ["Avertissement"] = "Waarschuwing",
        ["Information"] = "Informatie",
        ["Agenda"] = "Agenda",
        ["Indisponibilité"] = "Onbeschikbaarheid",
        ["Lunch"] = "Lunch",
        ["Heure de fin"] = "Einduur",
        ["Durée (minutes)"] = "Duur (minuten)",
        ["Début de journée"] = "Begin van de dag",
        ["Fin de journée"] = "Einde van de dag",
        ["Choisissez une date."] = "Kies een datum.",
        ["Choisissez l’heure de début et de fin."] = "Kies begin- en einduur.",
        ["Heures invalides."] = "Ongeldige uren.",
        ["L’heure de fin doit être après l’heure de début."] = "Einduur moet na beginuur liggen.",
        ["Sélectionnez une ligne à supprimer."] = "Selecteer een rij om te verwijderen.",
        ["Workspace introuvable."] = "Workspace niet gevonden.",
        ["PARAFacto — Erreur"] = "PARAFacto — Fout",
        ["Ouvrir la page"] = "Pagina openen",
        ["Ouvrir le dossier"] = "Map openen",
        ["Ouvrir l'onglet Données techniques"] = "Tabblad Technische Gegevens openen",
        ["Une nouvelle version de la politique de confidentialité et/ou des conditions d'utilisation est fournie avec cette mise à jour. Ouvrez l'onglet « Données techniques » (bouton ci-dessous), lisez les textes et acceptez-les — vous ne pourrez pas utiliser les autres onglets tant que ce n'est pas fait. Merci aussi d'ajouter une adresse e-mail d'envoi des copies de vos documents PDF si vous le désirez (section courriel du même onglet)."] =
            "Er is een nieuwe versie van het privacybeleid en/of de gebruiksvoorwaarden bij deze update geleverd. Open het tabblad Technische Gegevens (knop hieronder), lees de teksten en aanvaard ze — u kunt de andere tabbladen niet gebruiken tot dit is gebeurd. Voeg indien gewenst ook een e-mailadres toe voor het verzenden van kopieën van uw PDF-documenten (e-mailgedeelte van hetzelfde tabblad).",
        ["Ouvrez l'onglet « Données techniques » (bouton ci-dessous), lisez et acceptez la politique de confidentialité ainsi que les conditions d'utilisation. Merci aussi d'ajouter une adresse e-mail d'envoi des copies de vos documents PDF si vous le désirez (section courriel du même onglet)."] =
            "Open het tabblad Technische Gegevens (knop hieronder), lees en aanvaard het privacybeleid en de gebruiksvoorwaarden. Voeg indien gewenst ook een e-mailadres toe voor het verzenden van kopieën van uw PDF-documenten (e-mailgedeelte van hetzelfde tabblad).",
        ["Les textes de la politique de confidentialité et/ou des conditions d'utilisation sont introuvables ou vides (installation incomplète ou version ancienne). Vous pouvez utiliser la console : suivez la bannière « nouvelle version » ou téléchargez la dernière version du site, puis réinstallez. Ensuite, revenez ici pour lire et accepter les documents."] =
            "De teksten van het privacybeleid en/of de gebruiksvoorwaarden ontbreken of zijn leeg (onvolledige installatie of oude versie). U kunt de console gebruiken: volg de banner « nieuwe versie » of download de nieuwste versie van de site en installeer opnieuw. Kom daarna hier terug om de documenten te lezen en te aanvaarden.",
        ["Les documents juridiques ont été mis à jour (nouvelle version publiée avec l'application). Lisez les textes ci-dessous, cochez les deux cases puis enregistrez votre acceptation — les autres onglets restent masqués par le message tant que ce n'est pas fait."] =
            "De juridische documenten zijn bijgewerkt (nieuwe versie meegeleverd met de applicatie). Lees de onderstaande teksten, vink beide vakjes aan en registreer uw aanvaarding — de andere tabbladen blijven verborgen door dit bericht tot dit is gebeurd.",
        ["Veuillez lire les documents ci-dessous, cocher les deux cases puis enregistrer votre acceptation."] =
            "Lees de onderstaande documenten, vink beide vakjes aan en registreer uw aanvaarding.",
        ["Fichiers juridiques introuvables dans le dossier d'installation (sous-dossier Legal). Réinstallez l'application ou contactez le support."] =
            "Juridische bestanden niet gevonden in de installatiemap (submap Legal). Installeer de applicatie opnieuw of neem contact op met de ondersteuning.",
        ["Impossible de charger les documents : "] =
            "Kan documenten niet laden: ",
        ["Cash patient :"] = "Cash patiënt:",
        ["Facturé patient :"] = "Gefactureerd patiënt:",
        ["Total tiers payant :"] = "Totaal derdebetaler:",
        ["Facturé mutuelle :"] = "Gefactureerd mutualiteit:",
        ["Montant total du jour :"] = "Totaalbedrag van de dag:",
        ["Jour"] = "Dag",
        ["Mois"] = "Maand",
        ["Année"] = "Jaar",
        ["Semaine"] = "Week",
        ["TOUTES"] = "ALLE",
        ["IMPAYEE"] = "ONBETAALD",
        ["PARTIELLE"] = "GEDEELTELIJK",
        ["PAYEE"] = "BETAALD",
        ["ACQUITTEE"] = "VEREFFEND",
        ["PERTE"] = "VERLIES",
        ["MODIFIEE"] = "GEWIJZIGD",
        ["PATIENT"] = "PATIËNT",
        ["MUTUELLE"] = "MUTUALITEIT",
        ["CREDIT_NOTE"] = "CREDITNOTA",
        ["Libellé"] = "Omschrijving",
        ["Statut"] = "Status",
        ["Adresse"] = "Adres",
        ["Ville"] = "Stad",
        ["Pays"] = "Land",
        ["Le mois "] = "De maand ",
        [" est modifiable."] = " is bewerkbaar.",
        [" est verrouillé car des factures existent déjà."] = " is vergrendeld omdat er al facturen bestaan.",
        ["Définissez une plage horaire pendant laquelle vous ne pouvez pas recevoir de rendez-vous. Elle apparaît en rouge dans le calendrier."] = "Stel een periode in waarin u geen afspraken kunt ontvangen. Die verschijnt in het rood in de kalender.",
        ["Prénom médecin"] = "Voornaam arts",
        ["Code médecin"] = "Code arts",
        ["Prénom médecin:"] = "Voornaam arts:",
        ["Code médecin:"] = "Code arts:",
        ["Date paiement"] = "Betaaldatum",
        ["Facturé à"] = "Gefactureerd aan",
        ["TOTAL ENREGISTRÉ"] = "TOTAAL GEREGISTREERD",
        ["PAYE"] = "BETAALD",
        ["PAYE : "] = "BETAALD: ",
        ["Toutes les périodes"] = "Alle periodes",
        ["De 'date' à 'date'"] = "Van 'datum' tot 'datum'",
        ["Année / Semaine"] = "Jaar / Week",
        ["Année / Mois"] = "Jaar / Maand",
        ["Année / Trimestre"] = "Jaar / Kwartaal",
        ["Dernière année complète"] = "Laatste volledige jaar",
        ["Année courante"] = "Huidig jaar",
        ["Trimestre courant"] = "Huidig kwartaal",
        ["Période sélectionnée"] = "Geselecteerde periode",
        ["Perte"] = "Verlies",
        ["Solde"] = "Saldo",
        ["Jour férié :"] = "Feestdag:",
        ["Ces horaires sont mémorisés au lancement suivant. La liste « Heure de début » s’y adapte. Les RDV déjà enregistrés hors plage restent inchangés jusqu’à modification manuelle."] = "Deze uren worden bewaard voor de volgende start. De lijst \"Startuur\" past zich eraan aan. Reeds geregistreerde afspraken buiten dit bereik blijven ongewijzigd tot handmatige wijziging.",
        ["Tarif RDV:"] = "Afsprakentarief:",
        ["Données professionnelles"] = "Praktijkgegevens",
        ["Ces informations apparaissent sur les factures patients, notes de crédit, factures acquittées et états récapitulatifs mutuelles. Le logo et le titre sont aussi affichés dans la console."] = "Deze gegevens verschijnen op patiëntfacturen, creditnota\u2019s, vereffende facturen en mutualiteits-overzichten. Het logo en de titel worden ook op het dashboard getoond.",
        ["Recharger depuis le disque"] = "Opnieuw laden van schijf",
        ["Logo (aperçu)"] = "Logo (voorbeeld)",
        ["Choisir une image…"] = "Afbeelding kiezen\u2026",
        ["Retirer le logo"] = "Logo verwijderen",
        ["Console — titre à côté du logo"] = "Dashboard — titel naast het logo",
        ["Factures / NC — nom ou titre du praticien (ligne principale)"] = "Facturen / creditnota\u2019s — naam of titel zorgverlener (hoofdlijn)",
        ["Rappels factures (signature WhatsApp / mail)"] = "Factuurherinneringen (handtekening WhatsApp / e-mail)",
        ["Adresse et coordonnées (bloc facture patient)"] = "Adres en contact (blok patiëntfactuur)",
        ["Adresse ligne 1"] = "Adres regel 1",
        ["Adresse ligne 2 (ex. CP Ville)"] = "Adres regel 2 (bijv. postcode, gemeente)",
        ["N° INAMI"] = "RIZIV-nummer",
        ["N° TVA"] = "BTW-nummer",
        ["E-mail"] = "E-mail",
        ["Paiements (IBAN / BIC)"] = "Betalingen (IBAN / BIC)",
        ["IBAN (factures patients / NC)"] = "IBAN (patiëntfacturen / creditnota\u2019s)",
        ["IBAN (état mutuelle)"] = "IBAN (mutualiteitsoverzicht)",
        ["IBAN (notes de crédit — optionnel)"] = "IBAN (creditnota\u2019s — optioneel)",
        ["État récapitulatif mutuelle"] = "Samenvattend mutualiteitsoverzicht",
        ["Ligne « Nom et prénom du prestataire » et adresse complète sur une seule ligne. Si l\u2019adresse dédiée est vide, les lignes 1 et 2 ci-dessus sont combinées."] = "Regel « Naam en voornaam van de zorgverlener » en volledig adres op één lijn. Als het aparte adres leeg is, worden regel 1 en 2 hierboven gecombineerd.",
        ["Nom et prénom (ex. DUPONT Jean)"] = "Naam en voornaam (bijv. JANSSENS Jan)",
        ["Adresse (une ligne, optionnel)"] = "Adres (één lijn, optioneel)",
    };
}
